### ISSUE TITLE
the build breaks after updation

### ISSUE THREAD

**Issue by pnaik1** [nodeshift-starters/nodejs-rest-http#216]
The code was working fine before updation . but the build is breaking after updation
npm start

> nodejs-rest-http@4.0.0 start /home/pnaik/NODESHIFT/nodejs-rest-http
> node .

/home/pnaik/NODESHIFT/nodejs-rest-http/node_modules/pino/lib/tools.js:298
      throw new Error('prettyPrint option is no longer supported, see the pino-pretty package (https://github.com/pinojs/pino-pretty)')
      ^

Error: prettyPrint option is no longer supported, see the pino-pretty package (https://github.com/pinojs/pino-pretty)
    at normalizeArgs (/home/pnaik/NODESHIFT/nodejs-rest-http/node_modules/pino/lib/tools.js:298:13)
    at pino (/home/pnaik/NODESHIFT/nodejs-rest-http/node_modules/pino/pino.js:86:28)
    at Object.<anonymous> (/home/pnaik/NODESHIFT/nodejs-rest-http/bin/www:28:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-rest-http@4.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs-rest-http@4.0.0 start script.

**Comment by helio-frota** [comment]
thanks for reporting

**Comment by helio-frota** [comment]
commit with the fix here https://github.com/nodeshift-starters/nodejs-rest-http/commit/9538ebba9c6400cef847b110d77cd1505bd940d7
